# Base image using Alpine
FROM mcr.microsoft.com/dotnet/aspnet:9.0-alpine AS base
WORKDIR /app

# Build image
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS build

# Install debugger only in dev environment
RUN apk add --no-cache curl bash unzip && \
    curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

COPY ["common.props", "/common.props"]
COPY ["Directory.Build.props", "/Directory.Build.props"]
COPY ["global.json", "/global.json"]
COPY modules/ /modules

WORKDIR /src
COPY src/ .
RUN dotnet restore "BBT.Workflow.HttpApi.Host/BBT.Workflow.HttpApi.Host.csproj"
WORKDIR "/src/BBT.Workflow.HttpApi.Host"
ARG configuration=Debug
RUN dotnet publish "BBT.Workflow.HttpApi.Host.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

# Final image
FROM mcr.microsoft.com/dotnet/sdk:9.0-alpine AS final
WORKDIR /app
COPY --from=build /app/publish .
COPY --from=build /vsdbg /vsdbg

EXPOSE 5000

CMD ["dotnet", "watch", "run", "--project", "BBT.Workflow.HttpApi.Host.csproj", "--urls", "http://+:5000"]